services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeco_front
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - aeco-network
    restart: always

networks:
  aeco-network:
    external: true

