services:
  app:
    container_name: aeco_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - aeco-network
    restart: unless-stopped

networks:
  aeco-network:
    external: true
