export const companies = [
  {
    id: 1,
    name: 'Tech Solutions SA',
    address: 'Av. Insurgentes 123',
    city: 'Ciudad de México',
    country: 'México',
    email: 'contacto@techsolutions.com',
    phone: '+52 55 1234 5678',
    representative: 'Carlos Pérez',
    status: true,
    machines: 25,
    rfc: 'TCH123456789',
    folio: 'TS001',
  },
  {
    id: 2,
    name: 'Innovatech Corp',
    address: 'Calle Futura 456',
    city: 'Monterrey',
    country: 'México',
    email: 'info@innovatech.com',
    phone: '+52 81 9876 5432',
    representative: 'Laura Gómez',
    status: true,
    machines: 18,
    rfc: 'INN987654321',
    folio: 'IT002',
  },
  {
    id: 3,
    name: 'MegaIndustries',
    address: 'Carrera 7 #45-10',
    city: 'Bogotá',
    country: 'Colombia',
    email: 'ventas@megaindustries.com',
    phone: '+57 1 7654 3210',
    representative: 'Jorge Ramírez',
    status: false,
    machines: 30,
    rfc: 'MGI654987321',
    folio: 'MI003',
  },
  {
    id: 4,
    name: 'SmartBuild Ltd',
    address: 'Avenida Central 89',
    city: 'Madrid',
    country: 'España',
    email: 'soporte@smartbuild.com',
    phone: '+34 91 123 4567',
    representative: 'Ana Martínez',
    status: true,
    machines: 12,
    rfc: 'SBL321654987',
    folio: 'SB004',
  },
  {
    id: 5,
    name: 'NextGen Solutions',
    address: 'Av. Paulista 1020',
    city: 'São Paulo',
    country: 'Brasil',
    email: 'contact@nextgensolutions.com',
    phone: '+55 11 99876 5432',
    representative: 'Marcos Silva',
    status: false,
    machines: 20,
    rfc: 'NGS852963741',
    folio: 'NG005',
  },
  {
    id: 6,
    name: 'EcoTech Industries',
    address: 'Green Park 22',
    city: 'Londres',
    country: 'Reino Unido',
    email: 'info@ecotech.com',
    phone: '+44 20 7946 0123',
    representative: 'Sarah Johnson',
    status: true,
    machines: 15,
    rfc: 'ETI741852963',
    folio: 'ET006',
  },
  {
    id: 7,
    name: 'BuildFast Corp',
    address: 'Sunset Blvd 500',
    city: 'Los Ángeles',
    country: 'EE.UU.',
    email: 'support@buildfast.com',
    phone: '+1 310 555 6789',
    representative: 'Michael Scott',
    status: true,
    machines: 28,
    rfc: 'BFC369258147',
    folio: 'BF007',
  },
  {
    id: 8,
    name: 'SoftDev Ltd',
    address: 'Plaza IT 15',
    city: 'Buenos Aires',
    country: 'Argentina',
    email: 'contacto@softdev.com',
    phone: '+54 11 4321 0987',
    representative: 'Lucía Fernández',
    status: false,
    machines: 22,
    rfc: 'SDL159357486',
    folio: 'SD008',
  },
  {
    id: 9,
    name: 'Global Logistics',
    address: 'Industrial Park 45',
    city: 'Toronto',
    country: 'Canadá',
    email: 'info@globallogistics.com',
    phone: '+1 416 777 1234',
    representative: 'James Brown',
    status: true,
    machines: 35,
    rfc: 'GLC753951486',
    folio: 'GL009',
  },
  {
    id: 10,
    name: 'CyberNet Inc',
    address: 'Tech Valley 88',
    city: 'Berlín',
    country: 'Alemania',
    email: 'support@cybernet.com',
    phone: '+49 30 5678 9012',
    representative: 'Hans Müller',
    status: true,
    machines: 40,
    rfc: 'CNI852147963',
    folio: 'CN010',
  },
]
